<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ClamAV.Managed.Async</RootNamespace>
    <AssemblyName>ClamAV.Managed.Async</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClamAV.Managed\ClamAV.Managed.csproj" />
  </ItemGroup>

</Project>