<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ClamAV.Managed</RootNamespace>
    <AssemblyName>ClamAV.Managed</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <allowUnsafeBlocks>true</allowUnsafeBlocks>
  </PropertyGroup>

</Project>