<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ClamAV.Managed.Samples.AsyncGui</RootNamespace>
    <AssemblyName>ClamAV.Managed.Samples.AsyncGui</AssemblyName>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClamAV.Managed.Async\ClamAV.Managed.Async.csproj" />
  </ItemGroup>

</Project>