<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ClamAV.Managed.Samples.Gui</RootNamespace>
    <AssemblyName>ClamAV.Managed.Samples.Gui</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClamAV.Managed\ClamAV.Managed.csproj" />
  </ItemGroup>

</Project>